[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/Login.py"
name = "Login"
icon = "ğŸ”"

[[pages]]
path = "pages/Signup.py"
name = "Signup"
icon = "ğŸ“"

[[pages]]
path = "pages/Reset_Password.py"
name = "Reset Password"
icon = "ğŸ”"

[[pages]]
path = "pages/Dashboard.py"
name = "Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Pricing.py"
name = "Pricing"
icon = "ğŸ’¸"

[[pages]]
path = "pages/About_Us.py"
name = "About Us"
icon = "ğŸ“–"

[[pages]]
path = "pages/Contact_Us.py"
name = "Contact Us"
icon = "ğŸ“"

[[pages]]
path = "pages/Careers.py"
name = "Careers"
icon = "ğŸš€"
